#!/bin/bash
# Sukender's Bash-Based Patcher (BBP)
# This script is a wrapper around bbp* (bbpdiff, bbppatch, bbpar)
# Dependencies, error codes, documentation: see "bbp_config.sh"
#
# Author: Sukender (Benoit Neil)
# Licence: WTFPL v2 (see COPYING.txt)

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"		# Script dir
source "$DIR/bbp_config.sh" || exit 4

if [[ "${1:-}" == "diff" ]] || [[ "${1:-}" == "sub" ]]; then
	shift
	"$diffTool" "$@"
	exit $?
fi
if [[ "${1:-}" == "patch" ]] || [[ "${1:-}" == "add" ]]; then
	shift
	"$patchTool" "$@"
	exit $?
fi
if [[ "${1:-}" == "ar" ]] || [[ "${1:-}" == "archive" ]]; then
	shift
	"$arTool" "$@"
	exit $?
fi
if [[ "${1:-}" == "info" ]]; then
	shift
	"$infoTool" "$@"
	exit $?
fi


if [[ "${1:-}" == "--version" ]] || [[ "${1:-}" == "version" ]]; then
	echo "$toolVersion"
	exit 0
fi
if [[ "${1:-}" == "--man" ]] || [[ "${1:-}" == "man" ]]; then
	displayDoc
	exit 0
fi

echo ""
echo "$toolName"
echo "Tools to patch directories."
echo ""
echo "Syntax:"
echo "  bbp TOOL [tools_arguments]"
echo "    Where TOOL is one of: diff, patch, ar, info"
echo "  bbp --version"
echo "    Displays a short (parsable) version information and exits."
echo "  bbp --help"
echo "    This help."
echo "  bbp --man"
echo "    Displays all documentation available and exits."
echo ""
echo "For more information on a tool, type:"
echo "   bbp TOOL --help"
echo "   Example: bbp diff --help"
echo ""

if [[ "${1:-}" == "--help" ]] || [[ "${1:-}" == "help" ]] || [[ "${1:-}" == "-h" ]]; then
	exit 0
else
	echo "Error: Please select your tool!"
	echo ""
	exit 1
fi
