#!/bin/bash
# Displays the delta tool used to generage a compressed binary diff (patch).
# Author: Sukender (Benoit Neil)
# Licence: WTFPL v2 (see COPYING.txt)

# Dependencies, error codes, documentation: see "bbp_config.sh"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"		# Script dir
source "$DIR/bbp_config.sh" || exit 4

# --------------------------------------------------------------------------------
# Parameters parsing and usage

positionalOption() {
	if [ -z "$patchfile" ]; then
		patchfile="$1"
	else
		echo "Unrecognized option: $1"
		exit 1
	fi
}

usage() {
	echo ""
	echo "$toolName"
	echo "Displays the delta tool used to generage a compressed binary diff (patch)."
	echo
	echo "Syntax:"
	echo "  info patchName"
	echo
	echo "Options:"
	echo
	echo "  -h, --help"
	echo "      Displays this help text and exits."
	echo "  --man"
	echo "      Displays all documentation available and exits."
	echo "  --version"
	echo "      Displays a short (parsable) version information and exits."
	# echo "  -g, --get URL"
	# echo "      Downloads URL as the patch to apply."
	# echo "  -v, --verbose"
	# echo "      Adds a level of verbosity (more information). Default level = $defaultVerbosity."
	# echo "  -q, --quiet"
	# echo "      Removes a level of verbosity (more information). Default level = $defaultVerbosity."
	# echo "      Please note that even level 0 is not absolutely quiet."
	echo "  --"
	echo "      Do not interpret any more arguments as options."
	echo
}


while [ "$#" -gt 0 ]; do
case "$1" in
	# -v|--verbose)
		# shift; verbosity=$(( verbosity + 1 ));
		# ;;
	# -q|--quiet)
		# shift; verbosity=$(( verbosity - 1 ));
		# ;;
	-h|--help)
		shift; usage; exit 0;
		;;
	--man)
		shift; usage; displayDoc; exit 0;
		;;
	--version)
		shift; echo "$toolVersion"; exit 0;
		;;
	# -g|--get)
		# shift; patchUrl="$1"; shift;
		# ;;
	--)
		shift;
		break;
		;;
	# an option argument, continue
	*)
		positionalOption "$1"
		shift;
		;;
esac
done

if [ -z "$patchfile" ]; then
	usage;
	exit 1;
fi

# --------------------------------------------------------------------------------

# if [ -n "$patchUrl" ]; then
	# if (( $verbosity >= 1 )); then
		# echo $separatorDisplay
		# echo "[$(date +%H:%M:%S)] Getting the patch file."
		# echo ""
	# fi
	# wget "$patchUrl" -O "$patchfile" || exit 3
# fi

res="$(file -Zb "$patchfile")"
#if [[ "$res" ~= ^rdiff\  ]]; then
if [[ "$res" = "rdiff network-delta data" ]]; then
	echo "rdiff"
else
	if [[ "$res" = "VCDIFF binary diff" ]]; then
		echo "xdelta3"
	else
		echo "UNKNOWN_patch_format"
	fi
fi

